'use client';

import { useState, useEffect, useRef } from 'react';

const APK = 'https://github.com/Kroszborg/scry/releases/download/v1.1.0/app-release.apk';

// ─── Logo ─────────────────────────────────────────────────────────────────────
function LogoMark({ size = 24 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none">
      <rect x="1" y="1" width="30" height="30" rx="6" stroke="white" strokeWidth="1.5" />
      <rect x="7" y="7" width="4" height="18" rx="1.5" fill="white" opacity="0.9" />
      <rect x="13" y="7"  width="12" height="3"  rx="1" fill="white" />
      <rect x="13" y="12" width="9"  height="2.5" rx="1" fill="white" opacity="0.65" />
      <rect x="13" y="17" width="11" height="2.5" rx="1" fill="white" opacity="0.4" />
      <rect x="13" y="22" width="7"  height="2.5" rx="1" fill="white" opacity="0.25" />
    </svg>
  );
}

// ─── Icons ────────────────────────────────────────────────────────────────────
function DownloadIcon({ size = 14 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 15V3m0 12l-4-4m4 4l4-4M2 17l.621 2.485A2 2 0 0 0 4.561 21h14.878a2 2 0 0 0 1.94-1.515L22 17" />
    </svg>
  );
}

function ArrowRight({ size = 14 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M5 12h14M12 5l7 7-7 7" />
    </svg>
  );
}

// ─── Data ─────────────────────────────────────────────────────────────────────
const SCAN_MODES = ['NOTES', 'BOOK', 'RECEIPT', 'ID CARD', 'WHITEBOARD'] as const;

const CAPABILITIES = [
  {
    label: 'SCAN & OCR',
    items: [
      'Camera capture with live document frame overlay',
      'Import from photo library — JPEG, PNG, HEIC',
      'Gemini Vision OCR — real text extraction from images',
      'Persistent storage — scans survive app restarts',
      'Animated scan-line preview with mode switching',
    ],
  },
  {
    label: 'AI PROCESSING',
    items: [
      'Auto-generates title, category, and 3–5 tags',
      'Two-to-three sentence AI summary per document',
      'Clean text — OCR errors corrected automatically',
      '5–10 study flashcards generated in one tap',
      'Task, formula, and date extraction',
    ],
  },
  {
    label: 'EXPORT & STUDY',
    items: [
      'PDF export — formatted with title, summary, tags',
      'Markdown export — structured .md file',
      'Plain text share via any installed app',
      'Full-text search across all scanned documents',
      'AI chat — ask questions about any document',
    ],
  },
];

const FEATURES = [
  { n: '01', title: 'Gemini Vision OCR', desc: 'Images sent as base64 to Gemini 3 Flash for accurate, context-aware text extraction.' },
  { n: '02', title: 'Auto Title & Tags', desc: 'Every document gets a descriptive title and 3–5 relevant tags generated by AI.' },
  { n: '03', title: 'AI Summary', desc: '2–3 sentence summary generated for every processed document. Visible on the preview tab.' },
  { n: '04', title: 'Flashcard Generator', desc: '5–10 study flashcards covering key concepts, saved to the database per document.' },
  { n: '05', title: 'Task Extraction', desc: 'Pull all tasks, action items, to-dos, and deadlines out of any document in one tap.' },
  { n: '06', title: 'Formula Extraction', desc: 'Isolate mathematical equations, scientific notation, and formulas from textbooks.' },
  { n: '07', title: 'PDF Export', desc: 'Generates a formatted PDF with title, date, category, tags, summary, and body text.' },
  { n: '08', title: 'Markdown Export', desc: 'Exports structured .md file with front matter — title, tags, summary, and full text.' },
  { n: '09', title: 'AI Chat', desc: 'Streaming conversation about your document — powered by a ToolLoopAgent on Gemini.' },
  { n: '10', title: 'Full-Text Search', desc: 'Search across title, clean text, summary, and tags simultaneously.' },
  { n: '11', title: 'Category Filters', desc: 'Notes, Books, Receipts, IDs, Assignments, Whiteboards — filter the library by type.' },
  { n: '12', title: 'Editable Text', desc: 'Tap Edit on the Text tab to correct any OCR errors. Changes are saved to the database.' },
  { n: '13', title: 'Image Persistence', desc: 'All scans copied to documentDirectory on save — no broken images after restart.' },
  { n: '14', title: 'Scan Modes', desc: 'Notes, Book, Whiteboard, Receipt, ID Card — each tunes the AI processing prompt.' },
  { n: '15', title: 'Animated Scanner', desc: 'Live scan-line animation in the camera overlay. Corner guide markers for alignment.' },
  { n: '16', title: 'Turso Database', desc: 'LibSQL + Drizzle ORM. Documents and flashcards persisted across devices via cloud DB.' },
];

const STATS = [
  { value: '5',   label: 'Scan Modes' },
  { value: '16',  label: 'Features' },
  { value: '3',   label: 'Export Formats' },
  { value: '0',   label: 'Watermarks' },
  { value: 'AI',  label: 'OCR Engine' },
];

const STEPS = [
  { n: '01', title: 'Download the APK', desc: 'Tap the download button above. The file is approximately 65 MB and contains the full app.' },
  { n: '02', title: 'Enable unknown sources', desc: 'Settings → Apps → Special app access → Install unknown apps → enable for your browser or Files app.' },
  { n: '03', title: 'Open and install', desc: 'Find Scry.apk in your Downloads folder or notifications drawer. Tap it and follow the prompts.' },
];

// ─── Component ────────────────────────────────────────────────────────────────
export default function Home() {
  const [modeIdx, setModeIdx]   = useState(0);
  const [scrolled, setScrolled] = useState(false);
  const [copied, setCopied]     = useState(false);
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    intervalRef.current = setInterval(() => setModeIdx(m => (m + 1) % SCAN_MODES.length), 2000);
    return () => { if (intervalRef.current) clearInterval(intervalRef.current); };
  }, []);

  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 48);
    window.addEventListener('scroll', fn, { passive: true });
    return () => window.removeEventListener('scroll', fn);
  }, []);

  function copyAdb() {
    navigator.clipboard?.writeText('adb install Scry.apk').then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const mono: React.CSSProperties = {
    fontFamily: '"SF Mono", "Fira Code", "Fira Mono", "Roboto Mono", monospace',
  };

  return (
    <div style={{ background: '#0A0A0A', minHeight: '100vh', color: '#F0F0F0', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif' }}>

      <style>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        html { scroll-behavior: smooth; }
        ::selection { background: rgba(255,255,255,0.15); }
        @keyframes fadeUp {
          from { opacity: 0; transform: translateY(16px); }
          to   { opacity: 1; transform: none; }
        }
        @keyframes modeFade {
          0%       { opacity: 0; transform: translateY(8px); }
          15%, 85% { opacity: 1; transform: none; }
          100%     { opacity: 0; transform: translateY(-8px); }
        }
        .fade-up   { animation: fadeUp 0.6s cubic-bezier(0.16,1,0.3,1) both; }
        .fade-up-2 { animation: fadeUp 0.6s 0.12s cubic-bezier(0.16,1,0.3,1) both; }
        .fade-up-3 { animation: fadeUp 0.6s 0.24s cubic-bezier(0.16,1,0.3,1) both; }
        .mode-text { animation: modeFade 2s ease-in-out infinite; }
        .cap-card:hover  { background: #111 !important; }
        .feat-card:hover { background: #0F0F0F !important; }
        .btn-dl:hover    { opacity: 0.88 !important; transform: translateY(-1px) !important; }
        .btn-ghost:hover { border-color: #555 !important; color: #F0F0F0 !important; }
        .nav-link:hover  { color: #F0F0F0 !important; }
      `}</style>

      {/* ── Nav ─────────────────────────────────────────────────────────────── */}
      <nav style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
        height: 56, display: 'flex', alignItems: 'center', padding: '0 24px',
        background: scrolled ? 'rgba(10,10,10,0.92)' : 'transparent',
        backdropFilter: scrolled ? 'blur(16px)' : 'none',
        borderBottom: `1px solid ${scrolled ? '#1E1E1E' : 'transparent'}`,
        transition: 'all 0.2s',
      }}>
        <a href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
          <LogoMark size={26} />
          <span style={{ fontSize: 15, fontWeight: 700, letterSpacing: '-0.02em', color: '#F0F0F0' }}>Scry</span>
        </a>
        <div style={{ display: 'flex', gap: 28, marginLeft: 36 }}>
          {[['#capabilities', 'Features'], ['#features', 'Details'], ['#install', 'Install']].map(([h, l]) => (
            <a key={l} href={h} className="nav-link"
              style={{ ...mono, fontSize: 12, color: '#555', textDecoration: 'none', letterSpacing: '0.04em', textTransform: 'uppercase', transition: 'color 0.15s' }}>
              {l}
            </a>
          ))}
        </div>
        <div style={{ flex: 1 }} />
        <a href={APK} download className="btn-dl" style={{
          display: 'flex', alignItems: 'center', gap: 6,
          background: '#F0F0F0', color: '#0A0A0A', padding: '7px 14px',
          borderRadius: 6, fontSize: 13, fontWeight: 700, textDecoration: 'none',
          transition: 'all 0.15s',
        }}>
          <DownloadIcon size={13} /> Download APK
        </a>
      </nav>

      {/* ── Hero ─────────────────────────────────────────────────────────────── */}
      <section style={{ paddingTop: 140, paddingBottom: 96, paddingLeft: 24, paddingRight: 24, maxWidth: 1100, margin: '0 auto' }}>

        {/* Mode indicator */}
        <div className="fade-up" style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 40 }}>
          <div style={{ display: 'flex', gap: 5 }}>
            {SCAN_MODES.map((_, i) => (
              <div key={i}
                onClick={() => {
                  setModeIdx(i);
                  if (intervalRef.current) clearInterval(intervalRef.current);
                  intervalRef.current = setInterval(() => setModeIdx(m => (m + 1) % SCAN_MODES.length), 2000);
                }}
                style={{
                  width: i === modeIdx ? 20 : 6, height: 6, borderRadius: 3,
                  background: i === modeIdx ? '#F0F0F0' : '#2A2A2A',
                  transition: 'all 0.35s cubic-bezier(0.16,1,0.3,1)',
                  cursor: 'pointer',
                }}
              />
            ))}
          </div>
          <span style={{ ...mono, fontSize: 11, color: '#444', letterSpacing: '0.08em' }}>
            {SCAN_MODES[modeIdx]} MODE
          </span>
        </div>

        {/* Headline */}
        <div className="fade-up" style={{ marginBottom: 28 }}>
          <h1 style={{ fontSize: 'clamp(40px, 7vw, 82px)', fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1.02, color: '#F0F0F0' }}>
            Scan any document.
          </h1>
          <div style={{ position: 'relative', height: 'clamp(48px, 8.4vw, 98px)', overflow: 'hidden', marginBottom: 4 }}>
            {SCAN_MODES.map((m, i) => (
              <h1 key={m} className={i === modeIdx ? 'mode-text' : ''} style={{
                position: 'absolute', top: 0, left: 0,
                fontSize: 'clamp(40px, 7vw, 82px)', fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1.02,
                color: i === modeIdx ? '#F0F0F0' : 'transparent',
                opacity: i === modeIdx ? 1 : 0, pointerEvents: 'none',
              }}>
                {m.charAt(0) + m.slice(1).toLowerCase().replace(' card', ' Card')}.
              </h1>
            ))}
          </div>
          <h1 style={{ fontSize: 'clamp(40px, 7vw, 82px)', fontWeight: 800, letterSpacing: '-0.04em', lineHeight: 1.02, color: '#333' }}>
            Understand it with AI.
          </h1>
        </div>

        <p className="fade-up-2" style={{ fontSize: 18, lineHeight: 1.65, color: '#666', maxWidth: 520, marginBottom: 36 }}>
          OCR, AI summaries, flashcard generation, PDF export — all from your phone camera. No account. Free.
        </p>

        <div className="fade-up-3" style={{ display: 'flex', gap: 12, flexWrap: 'wrap', marginBottom: 72 }}>
          <a href={APK} download className="btn-dl" style={{
            display: 'flex', alignItems: 'center', gap: 8,
            background: '#F0F0F0', color: '#0A0A0A', padding: '13px 24px',
            borderRadius: 8, fontSize: 15, fontWeight: 800, textDecoration: 'none',
            transition: 'all 0.15s',
          }}>
            <DownloadIcon size={15} /> Download APK — Free
          </a>
          <a href="#install" className="btn-ghost" style={{
            display: 'flex', alignItems: 'center', gap: 7,
            border: '1px solid #222', color: '#888', padding: '13px 22px',
            borderRadius: 8, fontSize: 15, fontWeight: 500, textDecoration: 'none',
            transition: 'all 0.15s',
          }}>
            How to install <ArrowRight />
          </a>
        </div>

        {/* Stats */}
        <div style={{ display: 'flex', gap: 0, borderTop: '1px solid #1A1A1A', paddingTop: 32, flexWrap: 'wrap' }}>
          {STATS.map((s, i) => (
            <div key={s.label} style={{
              paddingRight: 32, marginRight: i < STATS.length - 1 ? 32 : 0,
              borderRight: i < STATS.length - 1 ? '1px solid #1A1A1A' : 'none',
              marginBottom: 16,
            }}>
              <div style={{ fontSize: 26, fontWeight: 800, letterSpacing: '-0.03em', color: '#F0F0F0', lineHeight: 1 }}>{s.value}</div>
              <div style={{ ...mono, fontSize: 10, color: '#444', marginTop: 5, letterSpacing: '0.06em', textTransform: 'uppercase' }}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Capabilities ─────────────────────────────────────────────────────── */}
      <section id="capabilities" style={{ borderTop: '1px solid #141414', padding: '72px 24px', maxWidth: 1100, margin: '0 auto' }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ ...mono, fontSize: 11, color: '#333', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>
            WHAT IT DOES
          </div>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 46px)', fontWeight: 800, letterSpacing: '-0.03em', color: '#F0F0F0' }}>
            One app. Three stages.
          </h2>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 1, background: '#141414', border: '1px solid #141414', borderRadius: 10, overflow: 'hidden' }}>
          {CAPABILITIES.map(cap => (
            <div key={cap.label} className="cap-card" style={{ background: '#0A0A0A', padding: '32px 28px', transition: 'background 0.15s' }}>
              <div style={{ ...mono, fontSize: 10, color: '#444', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 20 }}>
                {cap.label}
              </div>
              <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 12 }}>
                {cap.items.map(item => (
                  <li key={item} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                    <span style={{ width: 1, height: 14, background: '#333', flexShrink: 0, marginTop: 5 }} />
                    <span style={{ fontSize: 13, color: '#999', lineHeight: 1.6 }}>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* ── Feature grid ─────────────────────────────────────────────────────── */}
      <section id="features" style={{ borderTop: '1px solid #141414', padding: '72px 24px', maxWidth: 1100, margin: '0 auto' }}>
        <div style={{ marginBottom: 48 }}>
          <div style={{ ...mono, fontSize: 11, color: '#333', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>
            16 FEATURES
          </div>
          <h2 style={{ fontSize: 'clamp(28px, 4vw, 46px)', fontWeight: 800, letterSpacing: '-0.03em', color: '#F0F0F0' }}>
            Built for students who mean it.
          </h2>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(310px, 1fr))', gap: 1, background: '#141414', border: '1px solid #141414', borderRadius: 10, overflow: 'hidden' }}>
          {FEATURES.map(f => (
            <div key={f.n} className="feat-card" style={{ background: '#0A0A0A', padding: '22px 20px', transition: 'background 0.15s' }}>
              <div style={{ ...mono, fontSize: 11, color: '#2A2A2A', letterSpacing: '0.05em', marginBottom: 9 }}>{f.n}</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: '#F0F0F0', letterSpacing: '-0.01em', marginBottom: 6 }}>{f.title}</div>
              <div style={{ fontSize: 12, color: '#555', lineHeight: 1.6 }}>{f.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Install ──────────────────────────────────────────────────────────── */}
      <section id="install" style={{ borderTop: '1px solid #141414', padding: '72px 24px' }}>
        <div style={{ maxWidth: 600, margin: '0 auto' }}>
          <div style={{ marginBottom: 48 }}>
            <div style={{ ...mono, fontSize: 11, color: '#333', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 12 }}>
              SIDELOAD GUIDE
            </div>
            <h2 style={{ fontSize: 'clamp(26px, 4vw, 42px)', fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 12, color: '#F0F0F0' }}>
              Install in three steps.
            </h2>
            <p style={{ fontSize: 14, color: '#555', lineHeight: 1.65 }}>
              No Google Play required. Works on any Android 9.0+ device.
            </p>
          </div>

          <div>
            {STEPS.map((s, i) => (
              <div key={s.n}>
                {i > 0 && <div style={{ height: 1, background: '#141414' }} />}
                <div style={{ display: 'flex', gap: 20, padding: '28px 0' }}>
                  <div style={{ ...mono, fontSize: 12, color: '#2A2A2A', paddingTop: 2, minWidth: 20 }}>{s.n}</div>
                  <div>
                    <div style={{ fontSize: 15, fontWeight: 700, color: '#F0F0F0', letterSpacing: '-0.01em', marginBottom: 7 }}>{s.title}</div>
                    <div style={{ fontSize: 13, color: '#666', lineHeight: 1.7 }}>{s.desc}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* ADB block */}
          <div style={{ marginTop: 36, border: '1px solid #1A1A1A', borderRadius: 8, overflow: 'hidden' }}>
            <div style={{ padding: '11px 16px', borderBottom: '1px solid #141414', background: '#0D0D0D' }}>
              <span style={{ ...mono, fontSize: 10, color: '#333', letterSpacing: '0.08em' }}>ADB — DEVELOPER INSTALL</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, padding: '14px 16px', background: '#080808' }}>
              <code style={{ ...mono, fontSize: 13, color: '#666' }}>adb install Scry.apk</code>
              <button onClick={copyAdb} style={{
                ...mono, fontSize: 11, fontWeight: 600,
                background: copied ? 'rgba(74,222,128,0.1)' : '#141414',
                border: `1px solid ${copied ? 'rgba(74,222,128,0.3)' : '#222'}`,
                color: copied ? '#4ade80' : '#555',
                padding: '6px 12px', borderRadius: 5, cursor: 'pointer',
                transition: 'all 0.15s', whiteSpace: 'nowrap',
              }}>
                {copied ? 'Copied' : 'Copy'}
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────────────────────────── */}
      <section style={{ borderTop: '1px solid #141414', padding: '72px 24px', textAlign: 'center' }}>
        <div style={{
          maxWidth: 520, margin: '0 auto',
          border: '1px solid #1A1A1A', borderRadius: 14, padding: '52px 40px',
          background: '#0D0D0D',
        }}>
          <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 20 }}>
            <LogoMark size={44} />
          </div>
          <h2 style={{ fontSize: 'clamp(22px, 4vw, 36px)', fontWeight: 800, letterSpacing: '-0.03em', marginBottom: 12, color: '#F0F0F0' }}>
            Start scanning smarter.
          </h2>
          <p style={{ fontSize: 14, color: '#555', marginBottom: 28, lineHeight: 1.7 }}>
            Free forever. No account required. Scan documents, extract text with AI, generate flashcards, and export to PDF — all from your phone.
          </p>
          <a href={APK} download className="btn-dl" style={{
            display: 'inline-flex', alignItems: 'center', gap: 8,
            background: '#F0F0F0', color: '#0A0A0A', padding: '13px 28px',
            borderRadius: 8, fontSize: 15, fontWeight: 800, textDecoration: 'none',
            transition: 'all 0.15s', marginBottom: 18,
          }}>
            <DownloadIcon size={15} /> Download APK — Free
          </a>
          <div style={{ display: 'flex', justifyContent: 'center', gap: 20, flexWrap: 'wrap' }}>
            {['Android 9.0+', '~65 MB', 'v1.0.0', 'No account'].map(t => (
              <span key={t} style={{ ...mono, fontSize: 11, color: '#333' }}>{t}</span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────────────────── */}
      <footer style={{
        borderTop: '1px solid #141414', padding: '20px 24px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        flexWrap: 'wrap', gap: 14,
        maxWidth: 1100, margin: '0 auto',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <LogoMark size={18} />
          <span style={{ ...mono, fontSize: 11, color: '#333' }}>Scry &copy; {new Date().getFullYear()}</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap' }}>
          {[['#capabilities', 'Features'], ['#features', 'Details'], ['#install', 'Install'], [APK, 'Download']].map(([h, l]) => (
            <a key={l} href={h} download={l === 'Download' ? true : undefined}
              className="nav-link"
              style={{ ...mono, fontSize: 11, color: '#333', textDecoration: 'none', transition: 'color 0.15s' }}>
              {l}
            </a>
          ))}
          <span style={{ color: '#1E1E1E' }}>|</span>
          <a href="https://github.com/abhimanpanwar6/scry" target="_blank" rel="noopener noreferrer"
            className="nav-link"
            style={{ ...mono, fontSize: 11, color: '#333', textDecoration: 'none', transition: 'color 0.15s' }}>
            GitHub
          </a>
        </div>
      </footer>

    </div>
  );
}
